#!/bin/bash

(
  export DRASH_MODE="production"

  echo -e "\nDrash mode is: $DRASH_MODE\n"

  echo "Running build.ts..."
  deno $DRASH_DIRS_BASE/docs/.console/build.ts --allow-env --allow-read --allow-write $@

  echo "Deleting $DRASH_DIRS_BASE/docs/dist/public..."
  rm -rf $DRASH_DIRS_BASE/docs/dist/public

  echo "Making directories..."
  mkdir $DRASH_DIRS_BASE/docs/dist/public
  mkdir $DRASH_DIRS_BASE/docs/dist/public/assets
  mkdir $DRASH_DIRS_BASE/docs/dist/public/assets/css
  mkdir $DRASH_DIRS_BASE/docs/dist/public/assets/js
  mkdir $DRASH_DIRS_BASE/docs/dist/public/assets/vendor

  echo "Copying public assets to dist directory..."
  cp    $DRASH_DIRS_BASE/docs/public/assets/css/style-docs.css     $DRASH_DIRS_BASE/docs/dist/public/assets/css/style-docs.css
  cp    $DRASH_DIRS_BASE/docs/public/assets/css/style-docs.css.map $DRASH_DIRS_BASE/docs/dist/public/assets/css/style-docs.css.map
  cp    $DRASH_DIRS_BASE/docs/public/assets/js/bundle.js           $DRASH_DIRS_BASE/docs/dist/public/assets/js/bundle.js
  cp -r $DRASH_DIRS_BASE/docs/public/assets/vendor                 $DRASH_DIRS_BASE/docs/dist/public/assets/

  echo "Done building."
)
