#!/bin/bash

(
  export DRASH_MODE="production"

  echo -e "\nDrash mode is: $DRASH_MODE\n"

  echo "Building new webpack bundle with prod configs..."
  webpack --env.environment=production $@

  echo "Running build.ts..."
  deno $DRASH_DIR_ROOT/docs/.console/build.ts --allow-env --allow-read --allow-write $@

  echo "Done building."
)
