#!/bin/bash

$DRASH_DIR_ROOT/console/set_env_vars
deno_version=$(deno --version)
build_date=$(date)
export DRASH_DOCS_BASE_URL="/deno-drash"

echo "Performing production compilation of new webpack bundle.js"

node_modules/.bin/webpack \
  --env.environment="production" \
  --env.deno_version="$deno_version" \
  --env.base_url="$DRASH_DOCS_BASE_URL" \
  --env.build_date="$build_date" \
  --hide-modules
