#!/bin/bash

(
  export DRASH_MODE="development"

  echo -e "Don't forget to run the following:"
  echo -e "    \`npm run webpack-dev-watch\`"
  echo -e "    \`npm run watchmedo\`"
  echo -e ""

  deno $DRASH_DIR_ROOT/docs/docs.ts \
    --allow-net \
    --allow-env \
    --allow-read \
    $@
)
