import "./home_resource_test.ts";
import "./request_accepts_resource_test.ts";
import "./request_accepts_two_resource_test.ts";
import "./coffee_resource_test.ts";
import "./cookie_resource_test.ts";
import "./files_resource_test.ts";
import "./users_resource_test.ts";
import "./optional_path_params_test.ts";
import "./browser_request_resource_test.ts";
