localhost:1337/users/1?response_content_type=text/html&auth_token=shield
localhost:1337/users/2?response_content_type=text/html&auth_token=shield
localhost:1337/users/3?response_content_type=text/html&auth_token=shield
localhost:1337/users/1?response_content_type=text/html
localhost:1337/users/2?response_content_type=text/html
localhost:1337/users/3?response_content_type=text/html
localhost:1337/users/1?response_content_type=application/json&auth_token=shield
localhost:1337/users/2?response_content_type=application/json&auth_token=shield
localhost:1337/users/3?response_content_type=application/json&auth_token=shield
localhost:1337/users/1?response_content_type=application/json
localhost:1337/users/2?response_content_type=application/json
localhost:1337/users/3?response_content_type=application/json
localhost:1337/users/4
localhost:1337/users/4?response_content_type=text/html
localhost:1337/users/4?response_content_type=text/html&auth_token=shield
