import * as Drash from "../../mod.ts";

export interface IOptions {
  default_content_type?: string;
}

/**
 * This class represents a response that is generated by a resource -- to be
 * sent back to the client.
 */
export class DrashResponse extends Response {
  public headers = new Headers();
  public status = 200;
  #options: Drash.Interfaces.IResponseOptions = {};

  //////////////////////////////////////////////////////////////////////////////
  // FILE MARKER - METHODS - FACTORY ///////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////

  /**
   * See Drash.Interfaces.ICreateable.create().
   */
  constructor(options: Drash.Interfaces.IResponseOptions) {
    super()
    this.#options = options
    this.headers.set("Content-Type", options.default_response_content_type!)
  }
}
