curl localhost:8000/users/1?response_content_type=text/html&auth_token=shield
curl localhost:8000/users/2?response_content_type=text/html&auth_token=shield
curl localhost:8000/users/3?response_content_type=text/html&auth_token=shield
curl localhost:8000/users/1?response_content_type=text/html
curl localhost:8000/users/2?response_content_type=text/html
curl localhost:8000/users/3?response_content_type=text/html
curl localhost:8000/users/1?response_content_type=application/json&auth_token=shield
curl localhost:8000/users/2?response_content_type=application/json&auth_token=shield
curl localhost:8000/users/3?response_content_type=application/json&auth_token=shield
curl localhost:8000/users/1?response_content_type=application/json
curl localhost:8000/users/2?response_content_type=application/json
curl localhost:8000/users/3?response_content_type=application/json
curl localhost:8000/users/4
curl localhost:8000/users/4?response_content_type=text/html
curl localhost:8000/users/4?response_content_type=text/html&auth_token=shield
