/**
 * Drash - A micro HTTP framework for JavaScript and TypeScript systems.
 * Copyright (C) 2023  Drash authors. The Drash authors are listed in the
 * AUTHORS file at <https://github.com/drashland/drash/AUTHORS>. This notice
 * applies to Drash version 3.X.X and any later version.
 *
 * This file is part of Drash. See <https://github.com/drashland/drash>.
 *
 * Drash is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Drash is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Drash. If not, see <https://www.gnu.org/licenses/>.
 */

import { HTTPStatusCode } from "../types/HTTPStatusCode.ts";

/**
 * All HTTP response status codes from {@link https://developer.mozilla.org/en-US/docs/Web/HTTP/Status}.
 *
 * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTTP/Status} from more information on HTTP status codes.
 */
export enum StatusCode {
  Continue = 100,
  SwitchingProtocols = 101,
  Processing = 102,
  EarlyHints = 103,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultiStatus = 207,
  AlreadyReported = 208,
  IMUsed = 226,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Found = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  TemporaryRedirect = 307,
  PermanentRedirect = 308,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  PayloadTooLarge = 413,
  URITooLong = 414,
  UnsupportedMediaType = 415,
  RangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  Imateapot = 418,
  MisdirectedRequest = 421,
  UnprocessableEntity = 422,
  Locked = 423,
  FailedDependency = 424,
  TooEarly = 425,
  UpgradeRequired = 426,
  PreconditionRequired = 428,
  TooManyRequests = 429,
  RequestHeaderFieldsTooLarge = 431,
  UnavailableForLegalReasons = 451,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HTTPVersionNotSupported = 505,
  VariantAlsoNegotiates = 506,
  InsufficientStorage = 507,
  LoopDetected = 508,
  NotExtended = 510,
  NetworkAuthenticationRequired = 511,
}

export enum HTTPStatusCodeRedirection {
  MultipleChoices = 300,
  MovedPermanently = 301,
  Found = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  TemporaryRedirect = 307,
  PermanentRedirect = 308,
}

export const Status: {
  [k in keyof typeof StatusCode]: { Code: HTTPStatusCode; Description: string };
} = {
  Continue: { Code: 100, Description: "Continue" },
  SwitchingProtocols: { Code: 101, Description: "Switching Protocols" },
  Processing: { Code: 102, Description: "Processing" },
  EarlyHints: { Code: 103, Description: "Early Hints" },
  OK: { Code: 200, Description: "OK" },
  Created: { Code: 201, Description: "Created" },
  Accepted: { Code: 202, Description: "Accepted" },
  NonAuthoritativeInformation: {
    Code: 203,
    Description: "Non Authoritative Info",
  },
  NoContent: { Code: 204, Description: "No Content" },
  ResetContent: { Code: 205, Description: "Reset Content" },
  PartialContent: { Code: 206, Description: "Partial Content" },
  MultiStatus: { Code: 207, Description: "Multi Status" },
  AlreadyReported: { Code: 208, Description: "Already Reported" },
  IMUsed: { Code: 226, Description: "IM Used" },
  MultipleChoices: { Code: 300, Description: "Multiple Choices" },
  MovedPermanently: { Code: 301, Description: "Moved Permanently" },
  Found: { Code: 302, Description: "Found" },
  SeeOther: { Code: 303, Description: "See Other" },
  NotModified: { Code: 304, Description: "Not Modified" },
  UseProxy: { Code: 305, Description: "Use Proxy" },
  TemporaryRedirect: { Code: 307, Description: "Temporary Redirect" },
  PermanentRedirect: { Code: 308, Description: "Permanent Redirect" },
  BadRequest: { Code: 400, Description: "Bad Request" },
  Unauthorized: { Code: 401, Description: "Unauthorized" },
  PaymentRequired: { Code: 402, Description: "Payment Required" },
  Forbidden: { Code: 403, Description: "Forbidden" },
  NotFound: { Code: 404, Description: "Not Found" },
  MethodNotAllowed: { Code: 405, Description: "Method Not Allowed" },
  NotAcceptable: { Code: 406, Description: "Not Acceptable" },
  ProxyAuthenticationRequired: {
    Code: 407,
    Description: "Proxy Auth Required",
  },
  RequestTimeout: { Code: 408, Description: "Request Timeout" },
  Conflict: { Code: 409, Description: "Conflict" },
  Gone: { Code: 410, Description: "Gone" },
  LengthRequired: { Code: 411, Description: "Length Required" },
  PreconditionFailed: { Code: 412, Description: "Precondition Failed" },
  PayloadTooLarge: { Code: 413, Description: "Request Entity Too Large" },
  URITooLong: { Code: 414, Description: "Request URI Too Long" },
  UnsupportedMediaType: { Code: 415, Description: "Unsupported Media Type" },
  RangeNotSatisfiable: {
    Code: 416,
    Description: "Requested Range Not Satisfiable",
  },
  ExpectationFailed: { Code: 417, Description: "Expectation Failed" },
  Imateapot: { Code: 418, Description: "I'm a teapot" },
  MisdirectedRequest: { Code: 421, Description: "Misdirected Request" },
  UnprocessableEntity: { Code: 422, Description: "Unprocessable Entity" },
  Locked: { Code: 423, Description: "Locked" },
  FailedDependency: { Code: 424, Description: "Failed Dependency" },
  TooEarly: { Code: 425, Description: "Too Early" },
  UpgradeRequired: { Code: 426, Description: "Upgrade Required" },
  PreconditionRequired: { Code: 428, Description: "Precondition Required" },
  TooManyRequests: { Code: 429, Description: "Too Many Requests" },
  RequestHeaderFieldsTooLarge: {
    Code: 431,
    Description: "Request Header Fields Too Large",
  },
  UnavailableForLegalReasons: {
    Code: 451,
    Description: "Unavailable For Legal Reasons",
  },
  InternalServerError: { Code: 500, Description: "Internal Server Error" },
  NotImplemented: { Code: 501, Description: "Not Implemented" },
  BadGateway: { Code: 502, Description: "Bad Gateway" },
  ServiceUnavailable: { Code: 503, Description: "Service Unavailable" },
  GatewayTimeout: { Code: 504, Description: "Gateway Timeout" },
  HTTPVersionNotSupported: {
    Code: 505,
    Description: "HTTP Version Not Supported",
  },
  VariantAlsoNegotiates: { Code: 506, Description: "Variant Also Negotiates" },
  InsufficientStorage: { Code: 507, Description: "Insufficient Storage" },
  LoopDetected: { Code: 508, Description: "Loop Detected" },
  NotExtended: { Code: 510, Description: "Not Extended" },
  NetworkAuthenticationRequired: {
    Code: 511,
    Description: "Network Authentication Required",
  },
};

export const StatusByCode: {
  [k: number]: { Code: HTTPStatusCode; Description: string };
} = {
  100: { Code: 100, Description: "Continue" },
  101: { Code: 101, Description: "Switching Protocols" },
  102: { Code: 102, Description: "Processing" },
  103: { Code: 103, Description: "Early Hints" },
  200: { Code: 200, Description: "OK" },
  201: { Code: 201, Description: "Created" },
  202: { Code: 202, Description: "Accepted" },
  203: { Code: 203, Description: "Non Authoritative Info" },
  204: { Code: 204, Description: "No Content" },
  205: { Code: 205, Description: "Reset Content" },
  206: { Code: 206, Description: "Partial Content" },
  207: { Code: 207, Description: "Multi Status" },
  208: { Code: 208, Description: "Already Reported" },
  226: { Code: 226, Description: "IM Used" },
  300: { Code: 300, Description: "Multiple Choices" },
  301: { Code: 301, Description: "Moved Permanently" },
  302: { Code: 302, Description: "Found" },
  303: { Code: 303, Description: "See Other" },
  304: { Code: 304, Description: "Not Modified" },
  305: { Code: 305, Description: "Use Proxy" },
  307: { Code: 307, Description: "Temporary Redirect" },
  308: { Code: 308, Description: "Permanent Redirect" },
  400: { Code: 400, Description: "Bad Request" },
  401: { Code: 401, Description: "Unauthorized" },
  402: { Code: 402, Description: "Payment Required" },
  403: { Code: 403, Description: "Forbidden" },
  404: { Code: 404, Description: "Not Found" },
  405: { Code: 405, Description: "Method Not Allowed" },
  406: { Code: 406, Description: "Not Acceptable" },
  407: { Code: 407, Description: "Proxy Auth Required" },
  408: { Code: 408, Description: "Request Timeout" },
  409: { Code: 409, Description: "Conflict" },
  410: { Code: 410, Description: "Gone" },
  411: { Code: 411, Description: "Length Required" },
  412: { Code: 412, Description: "Precondition Failed" },
  413: { Code: 413, Description: "Request Entity Too Large" },
  414: { Code: 414, Description: "Request URI Too Long" },
  415: { Code: 415, Description: "Unsupported Media Type" },
  416: { Code: 416, Description: "Requested Range Not Satisfiable" },
  417: { Code: 417, Description: "Expectation Failed" },
  418: { Code: 418, Description: "I'm a teapot" },
  421: { Code: 421, Description: "Misdirected Request" },
  422: { Code: 422, Description: "Unprocessable Entity" },
  423: { Code: 423, Description: "Locked" },
  424: { Code: 424, Description: "Failed Dependency" },
  425: { Code: 425, Description: "Too Early" },
  426: { Code: 426, Description: "Upgrade Required" },
  428: { Code: 428, Description: "Precondition Required" },
  429: { Code: 429, Description: "Too Many Requests" },
  431: { Code: 431, Description: "Request Header Fields Too Large" },
  451: { Code: 451, Description: "Unavailable For Legal Reasons" },
  500: { Code: 500, Description: "Internal Server Error" },
  501: { Code: 501, Description: "Not Implemented" },
  502: { Code: 502, Description: "Bad Gateway" },
  503: { Code: 503, Description: "Service Unavailable" },
  504: { Code: 504, Description: "Gateway Timeout" },
  505: { Code: 505, Description: "HTTP Version Not Supported" },
  506: { Code: 506, Description: "Variant Also Negotiates" },
  507: { Code: 507, Description: "Insufficient Storage" },
  508: { Code: 508, Description: "Loop Detected" },
  510: { Code: 510, Description: "Not Extended" },
  511: { Code: 511, Description: "Network Authentication Required" },
};
