#!/bin/bash

# This script only exists to run Deno in different OSs. This script runs in the
# CI to build the CJS and ESM libs.
(
  rm -rf .drashland/builds && \
  deno task build-intermediary && \
  # This will need to be moved into the script for cross-builds
  # rm -rf node_modules && \
  # yarn install --no-lockfile && \
  deno task build-esm && \
  deno task build-cjs && \
  cp package.builds.json .drashland/builds/package.json && \
  rm -rf .drashland/builds/intermediary && \
  cd .drashland/builds && \
  yarn unlink && \
  yarn link && \
  cd ../..
)
