#!/bin/bash

(
  # Copy the source code
  cp -r $DRASH_DIR_ROOT/src $1

  # Copy the system-specific entry point file
  cp $DRASH_DIR_ROOT/system.ts $1

  cp $DRASH_DIR_ROOT/.gitignore $1

  cp $DRASH_DIR_ROOT/LICENSE $1

  cp $DRASH_DIR_ROOT/README.md $1

  cp $DRASH_DIR_ROOT/REQUIREMENTS.md $1
)
