#!/bin/bash

tags=(
v0.6.0-alpha
v0.6.0-alpha.1
v0.6.0-alpha.2
v0.6.0-alpha.3
v0.6.0-alpha.4
v0.6.0-alpha.5
v0.6.0-alpha.6
)

for i in "${tags[@]}"; do
  git push origin --delete $i
  git tag --delete $i
done
