#!/bin/bash

(
  deno run --allow-run --allow-write --allow-read https://deno.land/std@v0.23.0/prettier/main.ts $DRASH_DIR_ROOT/src
  deno run --allow-run --allow-write --allow-read https://deno.land/std@v0.23.0/prettier/main.ts $DRASH_DIR_ROOT/docs/src
)
