#!/bin/bash

(
  export DRASH_ROOT_DIR=$PWD
  deno --allow-net --allow-read --allow-write --allow-env tests/test.ts
  cd example_app
  deno --allow-net --allow-read --allow-write --allow-env app_test.ts
  cd -
)
